#!/bin/zsh
#agvtool new-marketing-version $1
#if [ $3 != "p" ] ; then
#	./build.sh
#fi
#cp ./build/Kort.ipa ./Kort.ipa
#agvtool new-marketing-version $1
#echo "Build Number: $BUILD_NUMBER"
#git add Kort.ipa
#git commit -m "iPA Update"
#git push
gh release create "Kort_$1" ./build/Kort.ipa --notes "$2"
